spring:
  datasource:
    url: jdbc:mysql://localhost:3306/phoneshop
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    time-zone: Asia/Phnom_Penh

jwt:
  rsa-private-key: classpath:private.pem
  rsa-public-key: classpath:public.pem

logging:
  level:
    "[org.springframework.security]": warn
    "[com.backend.phoneshop.config.security]": info
